[package]
authors = ["m4b <m4b.github.io@gmail.com>"]
name = "bingrep"
version = "0.4.1"
keywords = ["binary", "elf", "mach", "pe", "cross-platform"]
repository = "https://github.com/m4b/bingrep"
license = "MIT"
description = "Cross-platform binary parser and colorizer"
documentation = "https://docs.rs/bingrep"
readme = "README.md"
categories = ["command-line-utilities"]
include = ["src/**/*", "Cargo.toml", "Cargo.lock", "LICENSE", "README.md", "etc/*"]

[dependencies]
atty = "0.2"
hexplay = "0.2"
termcolor = "0.3"
structopt = "0.0.5"
structopt-derive = "0.0.5"
rustc-demangle = "0.1.5"
scroll = "0.7"
prettytable-rs = "0.6.7"
env_logger = "0.4.3"

[dependencies.goblin]
git = "https://github.com/m4b/goblin"
version = "0.0.12"

[dependencies.metagoblin]
git = "https://github.com/m4b/metagoblin"
version = "0.0.1"

[[bin]]
name = "bingrep"

[badges.travis-ci]
branch = "master"
repository = "m4b/bingrep"
