[package]
authors = ["m4b <m4b.github.io@gmail.com>"]
name = "bingrep"
version = "0.1.0"

[dependencies]
colored = "1.5.1"
structopt = "0.0.5"
structopt-derive = "0.0.5"

[dependencies.goblin]
version = "0.0.10"

[[bin]]
name = "bingrep"
