[package]
authors = ["m4b <m4b.github.io@gmail.com>"]
name = "bingrep"
version = "0.2.1"
readme = "README.md"
keywords = ["binary", "elf", "mach", "pe", "cross-platform"]
repository = "https://github.com/m4b/bingrep"
license = "MIT"
description = "Cross-platform binary parser and colorizer"
documentation = "https://docs.rs/bingrep"
categories = ["command-line-utilities"]
include = ["src/**/*", "Cargo.toml", "Cargo.lock", "LICENSE", "README.md", "etc/*"]

[dependencies]
colored = "1.5.1"
structopt = "0.0.5"
structopt-derive = "0.0.5"
rustc-demangle = "0.1.4"
scroll = "0.5"
prettytable-rs = "0.6.7"
term = "0.4.6"

[dependencies.goblin]
version = "0.0.10"

[[bin]]
name = "bingrep"

[badges.travis-ci]
branch = "master"
repository = "m4b/bingrep"
